import 'dotenv/config';
import express from 'express';
import OpenAI from 'openai';

const app = express();
app.disable('x-powered-by');
app.use(express.json({ limit: '64kb' }));

const REQUIRED_ENV = ['BLYNK_DEVICE_TOKEN', 'WEBHOOK_SECRET'];
const BLYNK_SERVER = (process.env.BLYNK_SERVER || 'https://blynk.cloud').replace(/\/$/, '');
const MODEL = process.env.OPENAI_MODEL || 'gpt-5.6-luna';
const PORT = Number(process.env.PORT || 3000);

function missingEnvironment() {
  return REQUIRED_ENV.filter((key) => !process.env[key]);
}

function clip(value, max = 220) {
  return String(value ?? '').replace(/\s+/g, ' ').trim().slice(0, max);
}

async function getBlynkValues() {
  const url = new URL(`${BLYNK_SERVER}/external/api/getAll`);
  url.searchParams.set('token', process.env.BLYNK_DEVICE_TOKEN);

  const response = await fetch(url, { headers: { accept: 'application/json' } });
  if (!response.ok) {
    throw new Error(`Blynk getAll failed: ${response.status} ${await response.text()}`);
  }
  return response.json();
}

async function updateBlynk(pin, value) {
  const url = new URL(`${BLYNK_SERVER}/external/api/update`);
  url.searchParams.set('token', process.env.BLYNK_DEVICE_TOKEN);
  url.searchParams.set(String(pin).toLowerCase(), clip(value));

  const response = await fetch(url);
  if (!response.ok) {
    throw new Error(`Blynk update ${pin} failed: ${response.status} ${await response.text()}`);
  }
}

function extractLine(text, label) {
  const regex = new RegExp(`^${label}:\\s*(.+)$`, 'im');
  const match = text.match(regex);
  return match ? match[1].trim() : '';
}

function fallbackAdvisory(values) {
  const condition = String(values.v4 ?? 'UNKNOWN').toUpperCase();
  const anomaly = clip(values.v8 ?? 'No anomaly message available', 160);
  const reason = clip(values.v10 ?? 'No condition reason available', 160);

  if (condition === 'CRITICAL') {
    return {
      summary: `CRITICAL prototype condition. ${reason}`,
      action: 'Stop the laboratory test if unsafe and verify the flagged sensor/parameter with a reference instrument.'
    };
  }

  if (condition === 'WARNING' || String(values.v9 ?? '0') === '1') {
    return {
      summary: `WARNING/anomaly detected. ${anomaly}`,
      action: 'Verify the flagged reading, sensor connection and recent trend before continuing the laboratory test.'
    };
  }

  return {
    summary: 'No active anomaly. Current prototype values are within the configured monitoring rules.',
    action: 'Continue monitoring and record baseline data for threshold validation.'
  };
}

async function openAIAdvisory(values) {
  if (!process.env.OPENAI_API_KEY) return null;

  const input = `
You are assisting with a university laboratory prototype for condition monitoring of a 33/11 kV mobile substation.

Constraints:
- Laboratory prototype only; not a protection or control system.
- Do not instruct operation, tripping, energising, isolation or switching of high-voltage equipment.
- Give only monitoring interpretation and safe laboratory checks.
- Thresholds and anomaly flags are generated by the ESP32 firmware.

Current Blynk values:
Temperature V0: ${values.v0 ?? 'N/A'} C
Humidity V1: ${values.v1 ?? 'N/A'} %RH
Voltage V2: ${values.v2 ?? 'N/A'} V
Current V3: ${values.v3 ?? 'N/A'} A
Overall condition V4: ${values.v4 ?? 'N/A'}
Power V5: ${values.v5 ?? 'N/A'} W
Frequency V6: ${values.v6 ?? 'N/A'} Hz
Power factor V7: ${values.v7 ?? 'N/A'}
Anomaly message V8: ${values.v8 ?? 'N/A'}
Anomaly flag V9: ${values.v9 ?? 'N/A'}
Condition reason V10: ${values.v10 ?? 'N/A'}

Return exactly two short lines under 180 characters each:
SUMMARY: <interpretation>
ACTION: <safe laboratory check>
`;

  const openai = new OpenAI({ apiKey: process.env.OPENAI_API_KEY });
  const response = await openai.responses.create({
    model: MODEL,
    input,
    max_output_tokens: 160
  });

  const text = response.output_text || '';
  return {
    summary: extractLine(text, 'SUMMARY') || clip(text),
    action: extractLine(text, 'ACTION') || 'Verify the flagged parameter with the laboratory reference instrument.'
  };
}

async function analysePrototype(values) {
  try {
    const ai = await openAIAdvisory(values);
    if (ai) return { ...ai, source: 'openai' };
  } catch (error) {
    console.error(`OpenAI advisory failed; using fallback: ${error.message}`);
  }
  return { ...fallbackAdvisory(values), source: 'rule-fallback' };
}

app.get('/', (req, res) => {
  res.json({
    service: 'blynk-render-bridge',
    endpoints: ['/health', '/ready', '/blynk-webhook'],
    openaiOptional: true
  });
});

app.get('/health', (req, res) => {
  const missing = missingEnvironment();
  res.set('Cache-Control', 'no-store');
  res.json({
    ok: true,
    service: 'blynk-render-bridge',
    configured: missing.length === 0,
    missing,
    openaiConfigured: Boolean(process.env.OPENAI_API_KEY)
  });
});

app.get('/ready', (req, res) => {
  const missing = missingEnvironment();
  res.set('Cache-Control', 'no-store');

  if (missing.length > 0) {
    return res.status(503).json({ ready: false, missing });
  }

  res.json({
    ready: true,
    blynkServer: BLYNK_SERVER,
    advisoryMode: process.env.OPENAI_API_KEY ? `OpenAI (${MODEL}) with fallback` : 'rule-based fallback'
  });
});

app.post('/blynk-webhook', async (req, res) => {
  try {
    const missing = missingEnvironment();
    if (missing.length > 0) {
      return res.status(503).json({ error: 'Bridge is not fully configured', missing });
    }

    const secret = req.get('x-webhook-secret');
    if (!secret || secret !== process.env.WEBHOOK_SECRET) {
      return res.status(401).json({ error: 'Unauthorized' });
    }

    const pin = String(req.body.pin || '').toUpperCase();
    const value = String(req.body.value ?? '');

    if (pin && pin !== 'V9') {
      return res.json({ ok: true, skipped: true, reason: 'Webhook is configured for V9 only.' });
    }

    const values = await getBlynkValues();
    const advisory = await analysePrototype(values);

    await Promise.all([
      updateBlynk('V11', advisory.summary),
      updateBlynk('V12', advisory.action)
    ]);

    res.json({
      ok: true,
      analysed: true,
      triggerValue: value,
      advisorySource: advisory.source
    });
  } catch (error) {
    console.error(error);
    res.status(500).json({ error: 'Bridge processing failed' });
  }
});

app.listen(PORT, () => {
  const missing = missingEnvironment();
  console.log(`Blynk-Render bridge listening on port ${PORT}`);
  if (missing.length > 0) console.warn(`Bridge is not ready. Missing: ${missing.join(', ')}`);
  if (!process.env.OPENAI_API_KEY) console.log('OPENAI_API_KEY not set: rule-based advisory fallback is active.');
});
